version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_BASE_URL=3.81.96.3:8000
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
