version: '3.8'

services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - KAFKA_HOST=0.0.0.0:9092
    volumes:
      - shared-data:/data
    networks:
      - app-network
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - ./conf/db/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - shared-data:/var/lib/postgresql/data
    networks:
      - app-network
      
  kafka-consumer:
    container_name: kafka-consumer
    build: ./kafka_consumer
    environment:
      - KAFKA_HOST=0.0.0.0:9092
    volumes:
      - shared-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
